
POST http://localhost:3000/messages 
Content-Type: application/json
{
  "chatRoomId": 2,
  "senderId": 2,
  "type": "text",
  "text": "Hello, this is my first message!"
}




GET http://localhost:3000/messages/1




