

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM0LCJlbWFpbCI6InBhc3N3b3JkdGVzdDRAZ21haWwuY29tIiwiaWF0IjoxNzQxNjg0NDg0LCJleHAiOjE3NDE2ODgwODQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.3K3SBkb2D7xku0xFpaQu63PeFGRIO_aClx_41v3qbcE


GET http://localhost:3000/users?page=1&limit=5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM0LCJlbWFpbCI6InBhc3N3b3JkdGVzdDRAZ21haWwuY29tIiwiaWF0IjoxNzQxNjg0NDg0LCJleHAiOjE3NDE2ODgwODQsImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.3K3SBkb2D7xku0xFpaQu63PeFGRIO_aClx_41v3qbcE


DELETE http://localhost:3000/users?id=33


POST http://localhost:3000/users
Content-Type: application/json
{
    "firstName": "testing",
    "lastName" : "interceptor",
    "email": "datastructure7667@gmail.com",
    "password": "@Ppassword23",
    "confirmpassword": "@Ppassword23"
}

PATCH http://localhost:3000/users
Content-Type: application/json
{
   "id": 33,
    "firstName": "test2",
    "lastName": "test2",
    "email": "aminubabafatima4@gmail.com",
    "userRole": "user"
}
