
GET http://localhost:3000/users


DELETE http://localhost:3000/users?id=1


POST http://localhost:3000/users
Content-Type: application/json
{
    "firstName": "Fatima",
    "lastName" : "Aminu",
    "email": "fatimaaminu14@gmail.com",
    "password": "33385",
    "confirmpassword": "password333485"
}

PATCH http://localhost:3000/users
Content-Type: application/json
{
    "id" : 1,
    "firstName" : "successfully ",
    "lastName" : "ttestingedite",
    "email" : "user1@gmail.com",
    "password" : "@Password869605"
}







