

GET http://localhost:3000/users
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjM0LCJ1c2VyUm9sZSI6InVzZXIiLCJlbWFpbCI6InBhc3N3b3JkdGVzdDRAZ21haWwuY29tIiwiaWF0IjoxNzQxNzEyMjc5LCJleHAiOjE3NDE3MTU4NzksImF1ZCI6ImxvY2FsaG9zdDozMDAwIiwiaXNzIjoibG9jYWxob3N0OjMwMDAifQ.NyEhU_2Hdk1ZneH0YXqYYCTbvlpbun_NWTUSwWxMWw0


GET http://localhost:3000/users?page=1&limit=3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsInVzZXJSb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJpYXQiOjE3NDE3NjU0MzAsImV4cCI6MTc0MTc2OTAzMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.638rXghtan7QFuFybjHk4g3VHM87tUQAgn8-K9k4ZwM


DELETE http://localhost:3000/users?id=33
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOjYsInVzZXJSb2xlIjoiYWRtaW4iLCJlbWFpbCI6ImFkbWluMUBnbWFpbC5jb20iLCJpYXQiOjE3NDE3NjU0MzAsImV4cCI6MTc0MTc2OTAzMCwiYXVkIjoibG9jYWxob3N0OjMwMDAiLCJpc3MiOiJsb2NhbGhvc3Q6MzAwMCJ9.638rXghtan7QFuFybjHk4g3VHM87tUQAgn8-K9k4ZwM


POST http://localhost:3000/users
Content-Type: application/json
{
    "firstName": "admin1",
    "lastName" : "admin1",
    "email": "admin1@gmail.com",
    "password": "admin1@Password",
    "confirmpassword": "admin1@Password",
    "userRole": "admin"
}

PATCH http://localhost:3000/users
Content-Type: application/json
{
   "id": 33,
    "firstName": "test2",
    "lastName": "test2",
    "email": "aminubabafatima4@gmail.com",
    "userRole": "user"
}
