import {
  IsString,
  IsEmail,
  IsNotEmpty,
  IsEnum,
  IsOptional,
  Validate,
  MaxLength,
  Matches,
  ValidatorConstraint,
  ValidatorConstraintInterface,
  ValidationArguments,
  IsArray,
  ValidateNested,
} from 'class-validator';
import { ApiProperty } from '@nestjs/swagger';
import { Column } from 'typeorm';
import { userRole } from '../Enums/userRole.enum';
import { Transform, Type } from 'class-transformer';
import { ChatRoom } from 'src/chatrooms/chatroom.entity';

/**
 * Custom validation to compare passwords
 */
@ValidatorConstraint({ name: 'MatchPasswords', async: false })
/**match passwordsconstraint class */
class MatchPasswordsConstraint implements ValidatorConstraintInterface {
  validate(confirmPassword: string, args: ValidationArguments): boolean {
    const object = args.object as CreateUserDto;
    if (!object.password) return false; // Ensure password is present
    return confirmPassword === object.password;
  }

  defaultMessage(args: ValidationArguments): string {
    return 'Password and confirm password do not match';
  }
}

/**
 * DTO for creating a user
 */
export class CreateUserDto {
  /**
   * First name field
   */
  @ApiProperty({
    type: 'string',
    example: 'Fatima',
  })
  @IsString()
  @IsNotEmpty()
  @MaxLength(100)
  firstName: string;

  /**
   * Last name field
   */
  @ApiProperty({
    type: 'string',
    example: 'Aminu',
  })
  @IsString()
  @IsOptional()
  @MaxLength(100)
  lastName: string;

  /**
   * Email field
   */
  @ApiProperty({
    type: 'string',
    example: 'fatimaaminu@mail.com',
  })
  @IsEmail()
  @MaxLength(150)
  @Column({ unique: true, length: 150 })
  email: string;

  /**
   * Password should contain numbers, alphabets, and uppercase
   */
  @ApiProperty({
    type: 'string',
    example: '@Password123',
    description: 'Password must include at least one uppercase letter, one lowercase letter, one number, and one special character.',
  })
  @IsString()
  @MaxLength(225)
  @Matches(
    /^(?=.*[!@#$%^&])(?=.*[a-z])(?=.*[A-Z])(?=.*[0-9])[a-zA-Z0-9!@#$%^&*]{8,16}$/,
    {
      message:
        'Password must include at least one uppercase letter, one lowercase letter, one number, and one special character.',
    },
  )
  password?: string;

  /**
   * Password confirmation field
   */
  @ApiProperty({
    type: 'string',
    example: '@Password123',
  })
  @IsString()
  @MaxLength(225)
  @Validate(MatchPasswordsConstraint)
  confirmpassword?: string;

  /**
   * User role
   */
  @ApiProperty({
    enum: userRole,
    example: userRole.USER,
  })
  @IsEnum(userRole)
  @IsOptional()
  @Transform(({ value }) => value ?? userRole.USER) 
  userRole?: userRole;

  /**
   * Autogenerated from Google when signing up with Google
   */
  @ApiProperty({
    type: 'string',
    example: 'poiuytrdspoiuytrewa\zxcvbnmml;poiuytrdsdcvbnm]'
  })
  @IsString()
  @IsOptional()
  @MaxLength(225)
  googleId?: string;

  /**
   * List of chatrooms associated with the user
   */
  @ApiProperty({
    type: 'array',
    items: { type: 'Chatroom' },
  })
  @IsOptional()
  @IsArray()
  @ValidateNested({ each: true })
  @Type(() => ChatRoom)
  chatRooms?: ChatRoom[];
}
